### PR TITLE
Additional text for FB posts

### PR DESCRIPTION
**Pull request by ZueFe**
Allows to grab additional text from facebook page when post was shared from external source

### CODE REVIEW

**Comment by ZueFe** [comment]
So this works on the shares from external source, where it shows this text: 
obrazek

And on shared posts where it shows this text: 
obrazek

Currently doesn't work on this kind of post which I assume is just shared image:
obrazek

**Comment by SokoMishaLov** [comment]
@ZueFe Hey! 
Thanks for your contribution :)
Actually I think that new field is some kind of “provider-specific”. ‘Post’ class should be as common as possible for all source providers.
I think it’s more appropriable to use concatenation for that two text fields and just use ‘text’ field (e.g. I did it in PikabuSkraper).

**Comment by ZueFe** [comment]
I split "addition text" into two strings since only one is actually displayed (first image) and second is just kinda...there...is more like first paragraph or some such, so figured concat is not the way to go.
With FB there also a possibility to have "commneted" shared post, so in "text" you'd have whatever the user wrote when sharing, and "additional text" is text from the source. 

But perhaps I can create extension for Post class for FB only, otherwise if it's concated, you will just end up splitting in anyway.

**Comment by ZueFe** [comment]
> 
> 
> @ZueFe Hey!
> Thanks for your contribution :)
> Actually I think that new field is some kind of “provider-specific”. ‘Post’ class should be as common as possible for all source providers.
> I think it’s more appropriable to use concatenation for that two text fields and just use ‘text’ field (e.g. I did it in PikabuSkraper).

I split "addition text" into two strings since only one is actually displayed (first image) and second is just kinda...there...is more like first paragraph or some such, so figured concat is not the way to go.
With FB there also a possibility to have "commneted" shared post, so in "text" you'd have whatever the user wrote when sharing, and "additional text" is text from the source.

But perhaps I can create extension for Post class for FB only, otherwise if it's concated, you will just end up splitting in anyway.

**Comment by SokoMishaLov** [comment]
@ZueFe Ah, I get it. 
I think that the comment of the shared post should be the main source of the `text` field. So I suppose it's ok.
About reposted data and attached articles - It's not a simple issue at all. Facebook provides just a small preview with the first paragraph and one tiny image, but most of the other sources do not have those features at all. And adding an extension/overriding is not the option in this case because Kotlin data classes are final (`Post`). And I do not like that proposal because one of the main goals of this project is to "equate" format of all sources we have (like RSS, but bit different and with some features).

I've been thinking a bit about this issue and have some thoughts and options about it:
1) Adding field with the list of all attached links of the post.
2) Adding new media type - `Unknown` with some link.
3) Adding new media type - `Article` with some link and optional preview text and image.
4) Leaving as is and just use concatenation for the text field with an ellipsis at the end of it.

**Comment by ZueFe** [comment]
@SokoMishaLov 
When it comes to small previews, there's a way to extract both strings and concat them together, so deffinately a possibility. They are both wrapped in div and span with human class names (as far as I remember).
A bummer aboout Post class tho :)
If I read you correctly, I think "Article" would work probably the best, similar "Video" and "Image" ones. Perhaps then video and image can have string description added to it? Not sure other pages would use it tho :/

I'll jump into making Article media class if that's ok then? We can try to figure out what to do with shared images in the meantime.

**Comment by SokoMishaLov** [comment]
@ZueFe just realized that making "Article" a new media type is a bad idea even so. "Article" cannot be a media file at all. It's some more complex than that. Sorry for confusing you :(
We need to find out a better solution I think.

**Comment by ZueFe** [comment]
@SokoMishaLov 
ah hm, well I don't really know the project structure that well, so no clue where it should go. Still with this PR I included link to original article, not the FB post, so it might help some 

In all fairness, by broad definition, medium is anything that transmits and/or conveys information ^^

**Comment by SokoMishaLov** [comment]
@ZueFe well, yeah, thank you anyway :)
I'm still thinking about the best solution to this case.
It's a good proposal about Medium, but it's not simple to implement because of the current data structure.
Medium and any other "blog" post should have ordered data. For now we just have text field and list of media, and filling it will not be good because of breaking text and media order.

**Comment by ZueFe** [comment]
@SokoMishaLov 
I see hm, well lemme know if you come up with something that will work, this is a rather important feature for app I'm making, would rather have it in the repo that is being regularly updated :)

**Comment by ZueFe** [comment]
Hey just curious, was there any progress on this?

**Comment by SokoMishaLov** [comment]
Hey, @ZueFe!
My apologies for being unavailable for such a long time.
Unfortunately, I didn't have enough time to work on this, but I still have some plans for this. 
I think that the additional media type like `UnknownLink` would be the best way.

**Comment by ZueFe** [comment]
@SokoMishaLov no worries, thanks for the answer, I will rewrite it when I find a little time then and send update PR once the conflicts are resolved.

**Pull request closed without merging**
